### ISSUE TITLE
disable/override logging

### ISSUE THREAD

**Issue by ChALkeR** [Daplie/le-sni-auto#3]
These lines:
```
le-sni-auto/index.js:151:        console.error('ERROR in le-sni-auto:');
le-sni-auto/index.js:152:        console.error(err.stack || err);
```
are printing error messages to console for any errors. It would be good if that could be disabled or overriden somehow, if one wants to have a common logging format.

I don't see any sense to override that, though, as the error is already passed to the callback function, and logging could (and should) be handled by the user.

So I suggest just removing those two lines whatsoever.

**Comment by coolaj86** [comment]
@ChALkeR You're right. I've created the issue over at https://git.daplie.com/Daplie/le-sni-auto/issues/3 and we'll get that republished this week.
